POST {{baseUrl}}/content
Content-Type: application/json

{
  "name": "my user"
}

###

POST {{baseUrl}}/content/list
Content-Type: application/json

{
  "facetFilters": [],
  "filter": "",
  "pagination": {
    "page": 0,
    "pageSize": 10
  }
}

###


POST {{baseUrl}}/content/list/stats
Accept: application/json

###


GET {{baseUrl}}/content/0d0a58caefb1409c8a0fff1957d7e019
Accept: application/json

###


POST {{baseUrl}}/sighting/claim
Content-Type: application/json

{
  "contentId": "0d0a58caefb1409c8a0fff1957d7e019",
  "weightedAssociationId":"5ed01fbdc89541aaa53386c51b500426"
}
###